In [1]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
     'Age':[np.nan,22,25,27],
     'City':['Pune','Pune',np.nan,'Hyd']}

df=pd.DataFrame(Data)
df

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [2]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',None],
     'Age':[None,22,25,27],
     'City':['Pune','Pune',None,'Hyd']}

df1=pd.DataFrame(Data)
df1

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  None
3     None  27.0   Hyd

In [3]:
df.to_csv('data_missing.csv',index=False)

In [4]:
df1.to_csv('data_missing_1.csv',index=False)

**dtypes**

In [5]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [6]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

**isnull**

In [7]:
df.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [8]:
df1.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [9]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [10]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**fillna**

In [11]:
df.fillna(30)   # Not recommended

     Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

In [12]:
df1.fillna(30)

     Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

- the above one is we are filling randomly
- all the columns are filled with random number
- it is not a good approach because in a data we have different data types

In [13]:
df['Age'].fillna(30)

0    30.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [14]:
df.fillna('Hyd')

     Names   Age  City
0   Ramesh   Hyd  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      Hyd  27.0   Hyd

In [15]:
df1.fillna('Hyd')

     Names   Age  City
0   Ramesh   Hyd  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      Hyd  27.0   Hyd

**What is difference between np.nan and None..?**

In [16]:
np.nan+5   # used for the Numerical purpose

nan

In [17]:
None+5    # used for the Categorical purpose

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [ ]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
np.nansum(arr1),np.sum(arr1)

In [ ]:
np.sum(arr2)

- np.nan represent float type
- None represents Object type
- if data operations related to Maths then nan format is better

**Fill the value based on column**

In [18]:
# df.fillna()
df['Names'].fillna('Manish')

0     Ramesh
1     Suresh
2    Sathish
3     Manish
Name: Names, dtype: object

**Fill with methods**

- whenenver we are using methods no need to provide values

- pad
- bfill
- ffill
- backfill

In [19]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],
     'Age':[np.nan,22,25,27],
     'City':['Pune','Pune',np.nan,'Hyd']}

df=pd.DataFrame(Data)
df

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [20]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [21]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad',axis=1)

     Names     Age  City
0   Ramesh  Ramesh  Pune
1   Suresh    22.0  Pune
2  Sathish    25.0  25.0
3      NaN    27.0   Hyd

In [22]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='bfill')

     Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [23]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='bfill',axis=1)

     Names   Age  City
0   Ramesh  Pune  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3     27.0  27.0   Hyd

In [24]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='ffill')

     Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [25]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='ffill',axis=1)

     Names     Age  City
0   Ramesh  Ramesh  Pune
1   Suresh    22.0  Pune
2  Sathish    25.0  25.0
3      NaN    27.0   Hyd

In [26]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='backfill')

     Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [27]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='backfill',axis=1)

     Names   Age  City
0   Ramesh  Pune  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3     27.0  27.0   Hyd

**Mean-Median-Mode**
- instead of filling with random values
- we can use mean median

In [28]:
age_mean=df['Age'].mean()
df['Age'].fillna(age_mean)

0    24.666667
1    22.000000
2    25.000000
3    27.000000
Name: Age, dtype: float64

In [29]:
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [30]:
mode=df['City'].mode()
mode

0    Pune
Name: City, dtype: object

# 25-09-2025

**KNN Immputer**

- K-Nearest Neighbours
- Where k=hyper parameters which means the user can change
- Idea: Instead of taking all the samples average
    - First fix the neighbours number i.e. k
    - Then find the neighbours using distance metric
    - Then take the average of those samples to fill the missing value

In [1]:
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer

In [2]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(x)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [3]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[3,np.nan,3],
   [np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,
                  weights='uniform')
imputer.fit_transform(x)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [4]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[3,np.nan,3],
   [np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,
                  weights='distance')
imputer.fit_transform(x)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])